// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZtmTimeTables.Data;

#nullable disable

namespace ZtmTimeTables.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221120155913_mg2")]
    partial class mg2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ZtmTimeTables.Entity.ZtmStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ZtmStops");
                });

            modelBuilder.Entity("ZtmTimeTables.Entity.ZtmVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ZtmVehicles");
                });

            modelBuilder.Entity("ZtmTimeTables.Entity.ZtmVehicleArrival", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ZtmStopId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ZtmStopId");

                    b.ToTable("ZtmVehicleArrivals");
                });

            modelBuilder.Entity("ZtmTimeTables.Entity.ZtmVehicleArrival", b =>
                {
                    b.HasOne("ZtmTimeTables.Entity.ZtmVehicle", "Vehicle")
                        .WithMany("Arrivals")
                        .HasForeignKey("VehicleId");

                    b.HasOne("ZtmTimeTables.Entity.ZtmStop", "ZtmStop")
                        .WithMany("VehicleArrivals")
                        .HasForeignKey("ZtmStopId");

                    b.Navigation("Vehicle");

                    b.Navigation("ZtmStop");
                });

            modelBuilder.Entity("ZtmTimeTables.Entity.ZtmStop", b =>
                {
                    b.Navigation("VehicleArrivals");
                });

            modelBuilder.Entity("ZtmTimeTables.Entity.ZtmVehicle", b =>
                {
                    b.Navigation("Arrivals");
                });
#pragma warning restore 612, 618
        }
    }
}
